django_verifications/urls.py
from django.urls import re_path
from django_verifications import views


app_name = "django_verifications"
urlpatterns = [
    re_path(r"^$", views.home, name="home"),
    re_path(r"^verify/(?P<model_name>.+)/(?P<pk>[0-9]+)$", views.verify, name="verify"),
    re_path(r"^verify/(?P<model_name>.+)$", views.verify, name="verify"),
    re_path(
        r"^set_as_incorrect/(?P<model_name>.+)/(?P<pk>[0-9]+)/(?P<field>.+)$",
        views.set_as_incorrect,
        name="set_as_incorrect",
    ),
    re_path(
        r"^correct/(?P<model_name>.+)/(?P<pk>[0-9]+)$", views.correct, name="correct"
    ),
    re_path(r"^correct/(?P<model_name>.+)$", views.correct, name="correct"),
]

testapp/urls.py
from django.conf.urls import include
from django.urls import re_path
from testapp import views


urlpatterns = [
    re_path(r"^login$", views.login, name="login"),
    re_path(r"^logout$", views.logout, name="logout"),
]

urlpatterns += [re_path(r"^verifications/", include("django_verifications.urls"))]

django_verifications/models.py
from builtins import object
import re

from django.db import models
from django.apps import apps
from django.contrib.auth.models import User
from django.db.models.signals import class_prepared
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType

from django_pewtils.abstract_models import BasicExtendedModel

from django_verifications.managers import VerificationManager, VerifiedModelManager
from django_verifications.exceptions import VerifiedFieldLock


class VerifiedModel(BasicExtendedModel):

    """
    An abstract model that is used to designate models in your own application that have one or more fields that
    need to be verified. Models that inherit from this class will have expanded `Meta` options that specify the
    objects and fields to be verified, and have a modified `save` function that protects verified fields from
    being modified.
    """

    objects = VerifiedModelManager().as_manager()

    class Meta(object):

        """
        Additional `Meta` attributes that are required for verification to function properly:
        - `fields_to_verify`: a list of field names corresponding to values that need to be verified
        - `verification_filters`: a list of dictionaries that will be applied as Django filters to select specific
        objects on the model
        """

        abstract = True

        fields_to_verify = []
        verification_filters = []

    def __init__(self, *args, **kwargs):
        """
        Modified `__init__` function to store the original value so that modifications can be tracked and rolled back
        if needed.
        :param args:
        :param kwargs:
        """

        super(VerifiedModel, self).__init__(*args, **kwargs)
        for field in self._meta.fields_to_verify:
            setattr(self, "__init_{}".format(field), getattr(self, field))

    def save(self, *args, **kwargs):

        """
        Modified `save` function that determines whether the object has been verified. If it has been, all verified
        values are checked and if any of them have been changed, a `VerifiedFieldLock` is raised and the save is
        aborted.
        :param args:
        :param kwargs:
        :return:
        """

        try:
            verifiable = self._meta.model.objects.flagged_for_verification().get(
                pk=self.pk
            )
        except self._meta.model.DoesNotExist:
            verifiable = False
        if verifiable:
            for field in self._meta.fields_to_verify:
                good_flags = self.verifications.filter(field=field).filter(is_good=True)
                bad_flags = (
                    self.verifications.filter(field=field)
                    .filter(is_good=False)
                    .filter(corrected=False)
                )
                if good_flags.count() > 0 and bad_flags.count() == 0:
                    original_val = getattr(self, "__init_{}".format(field))
                    current_val = getattr(self, field)
                    if original_val != current_val:
                        setattr(self, field, original_val)
                        raise VerifiedFieldLock(
                            "Cannot modify field {} on object {} due to existing verification (currently '{}', "
                            "attempted to replace with '{}')".format(
                                field, self, original_val, current_val
                            )
                        )

        super(VerifiedModel, self).save(*args, **kwargs)

    def get_verification_metadata(self):

        """
        Returns any information to be provided in the verification interface. The default version of this function
        returns all of the object's values, but this can be overwritten on your own model to return any dictionary
        of values you wish for coders to see in the interface alongside each object.

        :return: A dictionary of values to display in the verification interface
        """

        return list(self.model.objects.filter(pk=self.pk).values())[0]


class Verification(BasicExtendedModel):

    """
    Model that stores verifications. Contains the name of a field, a generic foreign key relation to the object that
    was verified, and the user that verified the field. Also contains any notes the user provided, and a flag
    indicating whether the value has been corrected, if it was originally marked as incorrect.
    """

    field = models.CharField(max_length=150)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="verifications"
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    is_good = models.BooleanField(null=True)
    notes = models.TextField(null=True)
    corrected = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    objects = VerificationManager().as_manager()


def add_verifications(sender, **kwargs):

    """
    Intercepts any models that inherit from `VerifiedModel` and automatically creates relations with the
    `Verification` model.
    :param sender:
    :param kwargs:
    :return:
    """

    if VerifiedModel in sender.__bases__:
        verifications = GenericRelation(
            Verification, related_query_name=re.sub(" ", "_", sender._meta.verbose_name)
        )
        verifications.contribute_to_class(sender, "verifications")


class_prepared.connect(add_verifications)

django_verifications/views.py
from __future__ import print_function
from __future__ import division
from builtins import str
import datetime

from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.forms import modelform_factory

from pewtils import is_not_null, decode_text
from django_pewtils import get_model
from pewtils import decode_text
from pewtils.io import FileHandler

from django_verifications.models import Verification
from django_verifications.exceptions import VerifiedFieldLock


@login_required
def home(request):

    verification_models = []
    for model_name in Verification.objects.available_model_names():

        row = {
            "name": model_name,
            "flagged_for_verification": Verification.objects.flagged_for_verification(
                model_name
            ).count(),
            "unexamined": Verification.objects.has_unexamined_fields(
                model_name
            ).count(),
            "need_correction": Verification.objects.any_field_incorrect(
                model_name
            ).count(),
            "finished": Verification.objects.all_fields_good_or_corrected(
                model_name
            ).count(),
        }
        if row["flagged_for_verification"] > 0:
            row["unexamined_pct"] = int(
                (float(row["unexamined"]) / float(row["flagged_for_verification"]))
                * 100
            )
            row["need_correction_pct"] = int(
                (float(row["need_correction"]) / float(row["flagged_for_verification"]))
                * 100
            )
            row["finished_pct"] = int(
                (float(row["finished"]) / float(row["flagged_for_verification"])) * 100
            )
        else:
            row["unexamined_pct"] = "--"
            row["need_correction_pct"] = "--"
            row["finished_pct"] = "--"
        verification_models.append(row)

    return render(
        request,
        "django_verifications/index.html",
        {"verification_models": verification_models},
    )


@login_required
def verify(request, model_name, pk=None):

    model_name = model_name.replace(" ", "_")

    model = get_model(model_name, app_name=settings.SITE_NAME)

    prev_id = None
    if request.method == "POST":

        prev_id = request.POST.get("pk")
        obj = model.objects.get(pk=prev_id)
        for field in model._meta.fields_to_verify:
            v = Verification.objects.create_or_update(
                {"user": request.user, "field": field, "content_object": obj},
                {
                    "timestamp": datetime.datetime.now(),
                    "is_good": eval(request.POST.get(field)),
                    "notes": request.POST.get("{}_notes".format(field)),
                    "corrected": False,
                },
                save_nulls=True,
            )
            print("Saving {}, {}: {} ({})".format(obj, field, v.is_good, v.pk))

    unexamined = Verification.objects.has_unexamined_fields(model_name)
    if not pk:
        if unexamined.count() > 0:
            new_obj = unexamined.order_by("?")[0]
        else:
            new_obj = None
    else:
        new_obj = model.objects.get(pk=pk)

    if new_obj:

        obj_data = {
            "fields_to_verify": [],
            "pk": new_obj.pk,
            "model_name": model_name,
            "num_remaining": unexamined.count(),
        }
        for field in model._meta.fields_to_verify:
            existing_verifications = (
                Verification.objects.filter(**{model_name: new_obj})
                .filter(user=request.user)
                .filter(field=field)
                .order_by("-timestamp")
            )
            note = ""
            existing_value = None
            if existing_verifications.count() > 0:
                note = existing_verifications[0].notes
                existing_value = (
                    str(int(existing_verifications[0].is_good))
                    if is_not_null(existing_verifications[0].is_good)
                    else None
                )

            obj_data["fields_to_verify"].append(
                (field, decode_text(getattr(new_obj, field)), existing_value, note)
            )

        obj_data["verification_metadata"] = new_obj.get_verification_metadata()

        obj_data["prev_id"] = prev_id

        return render(request, "django_verifications/verify.html", obj_data)

    else:

        return home(request)


@login_required
def set_as_incorrect(request, model_name, pk, field):

    model_name = model_name.replace(" ", "_")
    model = get_model(model_name, app_name=settings.SITE_NAME)
    obj = model.objects.get(pk=pk)
    v = Verification.objects.create_or_update(
        {"user": request.user, "field": field, "content_object": obj},
        {"timestamp": datetime.datetime.now(), "is_good": False, "corrected": False},
        save_nulls=True,
    )

    return correct(request, model_name, pk=pk)


@login_required
def correct(request, model_name, pk=None):

    model_name = model_name.replace(" ", "_")
    model = get_model(model_name, app_name=settings.SITE_NAME)

    prev_id = None
    if request.method == "POST":

        prev_id = request.POST.get("pk")
        obj = model.objects.get(pk=prev_id)

        existing_bad_verifications = (
            Verification.objects.filter(**{model_name: obj})
            .filter(field__in=model._meta.fields_to_verify)
            .filter(is_good=False)
            .filter(corrected=False)
            .order_by("-timestamp")
        )
        fields_to_update = list(
            set(existing_bad_verifications.values_list("field", flat=True))
        )

        Form = modelform_factory(model, fields=fields_to_update)
        form = Form(request.POST, instance=obj)

        for field in form:
            if hasattr(field.field, "queryset") and getattr(obj, field.name):
                form.fields[field.name].queryset.filter(pk=getattr(obj, field.name).pk)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.save(update_fields=fields_to_update)
            existing_bad_verifications.update(corrected=True)
            for field in fields_to_update:
                v = Verification.objects.create_or_update(
                    {"user": request.user, "field": field, "content_object": obj},
                    {"timestamp": datetime.datetime.now(), "is_good": True},
                    save_nulls=True,
                )

        else:
            raise Exception("Form was invalid!")

    bad = Verification.objects.any_field_incorrect(model_name)
    if not pk:
        if bad.count() > 0:
            new_obj = bad.order_by("?")[0]
        else:
            new_obj = None
    else:
        new_obj = model.objects.get(pk=pk)

    if new_obj:

        obj_data = {
            "pk": new_obj.pk,
            "model_name": model_name,
            "field_forms": [],
            "num_remaining": bad.count(),
        }

        obj_data["verification_metadata"] = new_obj.get_verification_metadata()
        obj_data["prev_id"] = prev_id

        Form = modelform_factory(model, fields=tuple(model._meta.fields_to_verify))
        for field in Form(instance=new_obj):
            existing_verifications = (
                Verification.objects.filter(**{model_name: new_obj})
                .filter(field=field.name)
                .order_by("-timestamp")
            )
            note, is_good = None, None
            if existing_verifications.count() > 0:
                note = "; ".join([v.notes for v in existing_verifications if v.notes])
                is_good = not bool(
                    existing_verifications.filter(is_good=False)
                    .filter(corrected=False)
                    .count()
                    > 0
                )
            if (
                hasattr(field.field, "queryset")
                and field.field.queryset
                and getattr(new_obj, field.name)
            ):
                field.field.queryset = field.field.queryset.filter(
                    pk=getattr(new_obj, field.name).pk
                )
            obj_data["field_forms"].append((field, is_good, note))

        return render(request, "django_verifications/correct.html", obj_data)

    else:

        return home(request)

django_verifications/templates/django_verifications/_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
        <title>Django Verifications</title>

        <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
        <style>
            body {
                padding-top: 60px;
            }
        </style>
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        {% block extra_head %}{% endblock %}

    </head>

    <body>

        {% block modals %}{% endblock %}

        {% if request.user and request.user.is_authenticated %}
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <div class="navbar-brand"><a href="{% url 'django_verifications:home' %}">Django Verifications</a></div>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% if request.user %}{{ request.user.coder.name }}{% endif %}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/">App Home</a></li>
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}

        <div class="container">

            {% block menu %}{% endblock %}
            {% block body %}{% endblock %}

        </div>

        <script src="http://d3js.org/d3.v3.min.js"></script>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.1/knockout-min.js"></script>

        {% block extra_body %}{% endblock %}

    </body>
</html>

django_verifications/templates/django_verifications/correct.html
{% extends "django_verifications/_template.html" %}

{% load static %}
{% load i18n widget_tweaks %}

{% block extra_head %}{% endblock %}

{% block modals %}{% endblock %}

{% block body %}

    <h3>Corrections: {{ model_name.title }} {{ pk }} {% if prev_id %}<a href="{% url 'django_verifications:correct' model_name prev_id %}">Go back</a>{% endif %}</h3>
    <small>{{ num_remaining }} left to correct</small>
    <form name='mturk_form' method='post' id='form' action="{% url 'django_verifications:correct' model_name %}">
        {% csrf_token %}
        <input type="hidden" name="pk" value="{{ pk }}">
        <div class="row">

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body" style="overflow: scroll; height: 450px;">
                        {% for k, v in verification_metadata.items %}
                            <p><b>{{ k }}:</b> {{ v|safe }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <table class="panel-body table table-condensed">
                        {% for field, is_good, note in field_forms %}
                            <tr class="{% if is_good %}success{% else %}danger{% endif %}"><td>
                                {% if field.errors %}
                                    <div class="form-group has-error">
                                        <label class="col-sm-2 control-label" for="id_{{ field.name }}">
                                            {{ field.label }}
                                        </label>
                                        <div class="col-sm-10">
                                            {% if is_good %}{{ field|attr:"class:form-control"|attr:"disabled" }}{% else %}{{ field|attr:"class:form-control" }}{% endif %}
                                            <span class="help-block">
                                                {% for error in field.errors %}{{ error }}{% endfor %}
                                            </span>
                                            {% if is_good %}
                                                <a href="{% url 'django_verifications:set_as_incorrect' model_name pk field.name %}" class="label-danger label">
                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="id_{{ field.name }}">
                                            {{ field.label }}
                                        </label>
                                        <div class="col-sm-10">
                                            {% if is_good %}{{ field|attr:"class:form-control"|attr:"disabled" }}{% else %}{{ field|attr:"class:form-control" }}{% endif %}
                                            {% if note %}
                                                <p class="help-block"><small>{{ note }}</small></p>
                                            {% endif %}
                                            {% if is_good %}
                                                <a href="{% url 'django_verifications:set_as_incorrect' model_name pk field.name %}" class="label-danger label">
                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endif %}
                            </td></tr>
                        {% endfor %}
                    </table>
                </div>

                <div class="panel panel-default">
                    <table class="panel-body table table-condensed">
                        <tr><td colspan="2"><button class="btn btn-primary btn-block" type="button" data-toggle="modal" data-target="#confirm_modal">Submit</button></td></tr>
                        <tr><td colspan="2"><a class="btn btn-danger btn-block" type="button" href="{% url 'django_verifications:correct' model_name %}">Skip</a></td></tr>
                    </table>
                </div>

            </div>
        </div>

        <div class="modal fade" id="confirm_modal" tabindex="-1" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Confirm submission</h4>
              </div>
              <div class="modal-body">
                <p>Are you sure you're ready to submit?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Go back</button>
                <button type="submit" id="submitButton" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </div>
        </div>

    </form>

{% endblock %}

{% block extra_body %}{% endblock %}

django_verifications/templates/django_verifications/index.html
{% extends "django_verifications/_template.html" %}

{% load static %}

{% block extra_head %}{% endblock %}

{% block modals %}{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Verification Tasks</h3>
                </div>
                <table class="panel-body table table-condensed">
                    <tr>
                        <th>Model</th>
                        <th>Total to Verify</th>
                        <th>Unexamined</th>
                        <th>Need Correction</th>
                        <th>Complete</th>
                        <th></th>
                        <th></th>
                    </tr>
                    {% for model in verification_models %}
                        <tr>
                            <td>{{ model.name.title }}</td>
                            <td>{{ model.flagged_for_verification }}</td>
                            <td>{{ model.unexamined }} ({{model.unexamined_pct}}%)</td>
                            <td>{{ model.need_correction }} ({{model.need_correction_pct}}%)</td>
                            <td>{{ model.finished }} ({{model.finished_pct}}%)</td>
                            <td>{% if model.unexamined > 0 %}<a class="btn btn-primary" href="{% url 'django_verifications:verify' model.name %}">Start Coding</a>{% endif %}</td>
                            <td>{% if model.need_correction > 0 %}<a class="btn btn-primary" href="{% url 'django_verifications:correct' model.name %}">Make Corrections</a>{% endif %}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_body %}{% endblock %}

django_verifications/templates/django_verifications/verify.html
{% extends "django_verifications/_template.html" %}

{% load static %}

{% block extra_head %}{% endblock %}

{% block modals %}{% endblock %}

{% block body %}

    <h3>Verification: {{ model_name.title }} {{ pk }} {% if prev_id %}<a href="{% url 'django_verifications:verify' model_name prev_id %}">Go back</a>{% endif %}</h3>
    <small>{{ num_remaining }} left to verify</small>
    <form name='mturk_form' method='post' id='form' action="{% url 'django_verifications:verify' model_name %}">
        {% csrf_token %}
        <input type="hidden" name="pk" value="{{ pk }}">
        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-body" style="overflow: scroll; height: 450px;">
                        {% for k, v in verification_metadata.items %}
                            <p><b>{{ k }}:</b> {{ v }}</p>
                        {% endfor %}
                    </div>
                </div>

            </div>
            <div class="col-md-7">
                {% for k, v, existing_value, note in fields_to_verify %}
                    <div class="panel panel-default">
                        <table class="panel-body table table-condensed">

                            <tr><td class="form-group col-md-4">{{ k }}</td><td class="form-group col-md-8">{{ v }}</td></tr>

                            <tr><td class="form-group col-md-4">Correct?</td><td class="form-group col-md-8">
                                <label class="radio-inline">
                                    <input class="zoom" type="radio" name="{{ k }}" value="True" {% if existing_value == '1' %}checked{% else %}{% endif %}>
                                    Correct
                                </label>
                                <label class="radio-inline">
                                    <input class="zoom" type="radio" name="{{ k }}" value="False" {% if existing_value == '0' %}checked{% else %}{% endif %}>
                                    Incorrect / Needs Review
                                </label>
                            </td></tr>

                            <tr><td class="form-group col-md-4">Notes</td><td class="form-group col-md-8">
                                <fieldset class="form-group">
                                    <textarea id="{{ k }}_notes" name="{{ k }}_notes" value="{% if note %}{{ note }}{% endif %}" class="form-control" rows="3" placeholder="Notes">{% if note %}{{ note }}{% endif %}</textarea>
                                </fieldset>
                            </td></tr>

                        </table>
                </div>
                {% endfor %}
                <div class="panel panel-default">
                    <table class="panel-body table table-condensed">
                        <tr><td colspan="2"><button class="btn btn-primary btn-block" type="button" data-toggle="modal" data-target="#confirm_modal">Submit</button></td></tr>
                        <tr><td colspan="2"><a class="btn btn-danger btn-block" type="button" href="{% url 'django_verifications:verify' model_name %}">Skip</a></td></tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="modal fade" id="confirm_modal" tabindex="-1" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Confirm submission</h4>
              </div>
              <div class="modal-body">
                <p>Are you sure you're ready to submit?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Go back</button>
                <button type="submit" id="submitButton" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </div>
        </div>

    </form>

{% endblock %}

{% block extra_body %}{% endblock %}